/** Row type for public.organizations */
export interface OrganizationRow {
  id: string;
  name: string;
  slug: string;
  plan: "starter" | "growth" | "enterprise";
  created_at: string;
  updated_at: string;
}

/** Row type for public.profiles */
export interface ProfileRow {
  id: string;
  org_id: string;
  role: "admin" | "analyst" | "executive";
  created_at: string;
  updated_at: string;
}

/** Config stored in runs.config (written incrementally by the worker) */
export interface RunConfig {
  /** Written by the API at run creation so the worker uses the correct plan limits. */
  plan_at_run_time?: "starter" | "growth" | "enterprise";
  /** Queries generated by the worker after profiling. */
  queries_used?: {
    text: string;
    source: "seenly_suggested" | "user_added";
    type:
      | "discovery"
      | "comparison"
      | "alternatives"
      | "educational"
      | "user_added";
    weight: number;
  }[];
  /** AI token usage written by the worker after querying. */
  ai_usage?: {
    ai_calls: number;
    tokens_in: number;
    tokens_out: number;
  };
}

/** Metadata stored in runs.results_meta */
export interface RunResultsMeta {
  /** Set when crawl failed and profiling fell back to project settings. */
  crawl_status?: "fallback";
  /** Total pipeline duration in milliseconds. */
  duration_ms?: number;
  /** Number of AI API calls made. */
  ai_calls?: number;
  /** Total prompt tokens consumed. */
  tokens_in?: number;
  /** Total completion tokens consumed. */
  tokens_out?: number;
  /** Error message if the run failed. */
  error?: string;
  traceback?: string;
}

/** Row type for public.runs */
export interface RunRow {
  id: string;
  org_id: string;
  created_by: string;
  status: "pending" | "queued" | "running" | "completed" | "failed";
  project_id: string | null;
  config: RunConfig | null;
  results_meta: RunResultsMeta | null;
  created_at: string;
  updated_at: string;
}

/** Row type for public.projects */
export interface ProjectRow {
  id: string;
  org_id: string;
  domain: string;
  name: string;
  sector: string | null;
  geo: string | null;
  created_at: string;
}

/** Row type for public.crawl_pages */
export interface CrawlPageRow {
  id: string;
  run_id: string;
  url: string;
  crawl_status: "ok" | "partial" | "blocked" | "unreachable";
  confidence: number | null;
  extraction_method: "html" | "js_render" | null;
  text_length: number | null;
  h1: string | null;
  h2s: string[] | null;
  has_faq: boolean;
  has_schema: boolean;
  schema_types: string[] | null;
  internal_link_count: number | null;
  page_quality_score: number | null;
  raw_html: string | null;
}

/** Row type for public.ai_results */
export interface AiResultRow {
  id: string;
  run_id: string;
  query: string;
  query_source: "seenly_suggested" | "user_added";
  query_type:
    | "discovery"
    | "comparison"
    | "alternatives"
    | "educational"
    | "user_added"
    | null;
  engine: "openai" | "anthropic" | "google";
  position: number | null;
  cited_domain: string | null;
  snippet: string | null;
  sentiment: "favorable" | "neutral" | "cautious" | "unfavorable" | null;
  is_target: boolean;
  is_degraded: boolean;
  raw_response: Record<string, unknown> | null;
}

/** Row type for public.run_scores (immutable after creation) */
export interface RunScoreRow {
  run_id: string;
  avs_score: number | null;
  aeo_score: number | null;
  sentiment_score: number | null;
  seenly_score_base: number | null;
  seenly_score_final: number | null;
  penalties_applied: string[];
  avs_confidence: number | null;
  aeo_confidence: number | null;
  completed_at: string;
}

/** Row type for public.competitors */
export interface CompetitorRow {
  id: string;
  run_id: string;
  domain: string;
  mention_count: number;
  query_count: number;
  avg_position: number | null;
}

/**
 * Supabase Database type definition.
 * Pass as generic to createClient<Database>() for typed queries.
 */
export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: OrganizationRow;
        Insert: Omit<OrganizationRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<OrganizationRow, "id">>;
        Update: Partial<Omit<OrganizationRow, "id" | "created_at">>;
        Relationships: [];
      };
      profiles: {
        Row: ProfileRow;
        Insert: Omit<ProfileRow, "created_at" | "updated_at">;
        Update: Partial<Omit<ProfileRow, "id" | "created_at">>;
        Relationships: [
          {
            foreignKeyName: "profiles_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      runs: {
        Row: RunRow;
        Insert: Omit<
          RunRow,
          | "id"
          | "created_at"
          | "updated_at"
          | "status"
          | "project_id"
          | "config"
          | "results_meta"
        > &
          Partial<
            Pick<
              RunRow,
              "id" | "status" | "project_id" | "config" | "results_meta"
            >
          >;
        Update: Partial<Omit<RunRow, "id" | "org_id" | "created_at">>;
        Relationships: [
          {
            foreignKeyName: "runs_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "runs_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      projects: {
        Row: ProjectRow;
        Insert: Omit<ProjectRow, "id" | "created_at"> &
          Partial<Pick<ProjectRow, "id">>;
        Update: Partial<Omit<ProjectRow, "id" | "org_id" | "created_at">>;
        Relationships: [
          {
            foreignKeyName: "projects_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      crawl_pages: {
        Row: CrawlPageRow;
        Insert: Omit<CrawlPageRow, "id"> & Partial<Pick<CrawlPageRow, "id">>;
        Update: Partial<Omit<CrawlPageRow, "id">>;
        Relationships: [
          {
            foreignKeyName: "crawl_pages_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "runs";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_results: {
        Row: AiResultRow;
        Insert: Omit<AiResultRow, "id"> & Partial<Pick<AiResultRow, "id">>;
        Update: Partial<Omit<AiResultRow, "id">>;
        Relationships: [
          {
            foreignKeyName: "ai_results_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "runs";
            referencedColumns: ["id"];
          },
        ];
      };
      run_scores: {
        Row: RunScoreRow;
        Insert: RunScoreRow;
        Update: Partial<RunScoreRow>;
        Relationships: [
          {
            foreignKeyName: "run_scores_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: true;
            referencedRelation: "runs";
            referencedColumns: ["id"];
          },
        ];
      };
      competitors: {
        Row: CompetitorRow;
        Insert: Omit<CompetitorRow, "id"> & Partial<Pick<CompetitorRow, "id">>;
        Update: Partial<Omit<CompetitorRow, "id">>;
        Relationships: [
          {
            foreignKeyName: "competitors_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "runs";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
